"""
UI-shell copy for the Flet Mini App (navigation, buttons, common labels).

Tour titles/descriptions still come from the API and may use fallback translation there.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Callable

# Keys per language; partial tables merge with English (see shell()).
_STR: dict[str, dict[str, str]] = {
    "en": {
        "catalog_title": "Tours catalog",
        "catalog_subtitle": "Main booking flow: browse here, then use My bookings for reservation and payment status. "
        "Optional filters below mirror the quick shortcuts in the bot chat.",
        "btn_my_bookings": "My bookings",
        "btn_language_settings": "Language & settings",
        "btn_help": "Help",
        "nav_custom_trip": "Custom or group trip",
        "filters_heading": "Filters",
        "label_destination": "Destination",
        "hint_destination": "Belgrade",
        "label_departure_from": "Departure from",
        "label_departure_to": "Departure to",
        "label_max_price": "Max price",
        "hint_date": "YYYY-MM-DD",
        "hint_price": "150",
        "btn_apply_filters": "Apply filters",
        "btn_clear": "Clear",
        "loading_tours": "Loading tours...",
        "empty_catalog": "No tours match the current filters. Try clearing one or more filters.",
        "view_details": "View details",
        "catalog_card_no_description": "Open the detail screen to see the full tour description.",
        "badge_seats_available": "Seats available",
        "badge_sold_out": "Sold out",
        "loading_tour_details": "Loading tour details...",
        "back_to_catalog": "Back to catalog",
        "settings": "Settings",
        "prepare_reservation": "Prepare reservation",
        "catalog_card_assisted_notice": "Whole-bus self-booking in the app is not available for this catalog departure. Open details to continue with our team and complete your booking.",
        "detail_assisted_booking_title": "Continue this catalog trip with our team",
        "detail_assisted_booking_body": "Full-bus self-service is not offered in the app for this departure. Use the button below or Help — we will assist you with this same catalog listing. "
        "This is catalog booking assistance, not a separate custom-trip or quote workflow.",
        "btn_request_full_bus_assistance": "Contact us about this catalog trip",
        "mode2_custom_trip_hint": "Need a different route, date, or group arrangement than this ready-made charter? Start a custom trip request — it is separate from this catalog departure and does not reserve this tour automatically.",
        "btn_mode2_request_custom_trip": "Request a custom trip",
        "preparation_assisted_title": "Full-bus self-booking is not available for this catalog departure",
        "preparation_assisted_body": "You cannot place or pay for a whole-bus hold yourself in the app for this catalog departure. Use Help to reach the team and continue booking with manual assistance.",
        "waitlist_intro_sold_out": "This tour is sold out. You can join the waitlist to record interest — "
        "this is not a confirmed booking or a guaranteed seat.",
        "waitlist_join_cta": "Join waitlist",
        "waitlist_status_on": "You are on the waitlist for this tour. This is not a confirmed booking.",
        "waitlist_active_title": "You are on the waitlist",
        "waitlist_active_body": "Your interest is recorded for this tour. This is not a confirmed booking or a guaranteed seat.",
        "waitlist_in_review_title": "Your waitlist request is being reviewed",
        "waitlist_in_review_body": "We are processing your request. This is still not a confirmed booking or a guaranteed seat.",
        "waitlist_closed_body": "Your previous waitlist request for this tour is closed. You can join the waitlist again if you still want to show interest — still not a confirmed booking.",
        "waitlist_tour_not_eligible": "This tour is not open for booking or waitlist from here right now.",
        "waitlist_snackbar_created": "Your waitlist request was recorded. This is not a confirmed booking.",
        "waitlist_snackbar_already": "You are already on the waitlist for this tour.",
        "waitlist_snackbar_not_eligible": "Waitlist is not available for this tour right now.",
        "waitlist_snackbar_error": "Could not record your waitlist request. Please try again later.",
        "fallback_translation_note": "No translation is available for your selected language for this tour; "
        "showing the next available language (see Language & settings).",
        "section_overview": "Overview",
        "section_program": "Program",
        "section_included": "Included",
        "section_excluded": "Not included",
        "section_boarding_points": "Boarding points",
        "boarding_no_details": "Boarding point details are not available for this tour yet.",
        "boarding_departure_time": "Departure time",
        "boarding_notes_fallback": "No extra notes for this boarding point.",
        "loading_reservation_options": "Loading reservation options...",
        "back_to_tour_details": "Back to tour details",
        "prep_note": "Pick seats and boarding, preview the summary, then confirm to create a temporary reservation "
        "(dev user {dev_id}). Payment entry follows on the next screen.",
        "label_seats": "Seats",
        "label_boarding": "Boarding point",
        "btn_preview_summary": "Preview summary",
        "btn_confirm_reservation": "Confirm reservation",
        "prep_summary_title": "Preparation summary",
        "prep_line_seats": "Seats: {n}",
        "prep_line_boarding": "Boarding point: {city}, {addr}",
        "prep_line_boarding_time": "Boarding time: {t}",
        "prep_line_estimated": "Estimated total: {amount} {currency}",
        "prep_hold_note": "Your seats are not held until you confirm. This creates a temporary hold; "
        "complete payment before the deadline on the next screens.",
        "loading_reservation": "Loading reservation...",
        "back_to_preparation": "Back to preparation",
        "reservation_confirmed_title": "Temporary hold confirmed",
        "reservation_hold_intro": "Your hold is active and payment is still required. Pay now before the deadline below or the seats may be released. Nothing is shown as paid until the server confirms it.",
        "continue_to_payment": "Continue to payment",
        "line_reservation_ref": "Reservation reference: #{id}",
        "line_amount_to_pay": "Amount to pay: {amount} {currency}",
        "line_payment_status": "Payment status: {status}",
        "starting_payment": "Starting payment entry...",
        "payment_title": "Payment",
        "payment_intro": "Reservation is temporary. Complete payment before the hold expires. "
        "Details below come from the server; payment is not marked successful until the backend confirms it.",
        "payment_intro_active_hold": "This hold is still active. Complete payment before the deadline below — after that, seats may be released back to the tour.",
        "payment_screen_unavailable_hold": "Payment cannot be started for this reservation. The hold may have expired or been released. Open My bookings for the current status, or start again from the catalog.",
        "payment_screen_load_error_generic": "We could not load the payment step. Go back to My bookings or try again.",
        "payment_mock_disabled_user_message": "Test payment completion is turned off on this server. Your booking stays unpaid until an operator or webhook confirms it. For staging tests, ask your team to enable mock payment on the API, or use the normal payment channel when available.",
        "payment_confirm_error_generic": "Payment could not be confirmed. Try again while the hold is still active, or check My bookings.",
        "booking_detail_note_active_hold": "You can still pay while the deadline above applies. After payment is confirmed, this booking moves to Confirmed bookings.",
        "booking_detail_note_confirmed": "This trip is paid and confirmed. Use My bookings if you need to review details.",
        "booking_detail_note_inactive_unpaid_reservation": "This reservation is no longer active — the hold ended without completed payment. To travel on this tour, start a new reservation from the catalog if seats are available.",
        "booking_detail_note_other_status": "Review the status above. Use My bookings to track updates, or log a support request if something looks wrong.",
        "booking_detail_note_released": "This hold is no longer active (expired or released without payment). To travel on this tour, start a new reservation from the catalog if seats are available.",
        "line_pay_before": "Pay before: {when}",
        "line_reservation_expiry_na": "Reservation expiry time is not available.",
        "line_amount_due": "Amount due: {amount} {currency}",
        "line_payment_session_ref": "Payment session reference: {ref}",
        "payment_stub_notice": "Provider checkout inside this app is not connected yet. "
        "Pay Now explains the next step; nothing is shown as paid until reconciliation confirms it.",
        "payment_success_title": "Payment confirmed",
        "payment_success_intro": "The server recorded your payment. Your seats are confirmed for this departure.",
        "payment_success_booking_status": "Booking status: confirmed.",
        "pay_now": "Pay now",
        "loading_bookings": "Loading bookings...",
        "my_bookings_title": "My bookings",
        "my_bookings_subtitle": "Confirmed trips appear first, then temporary reservations you can pay for, then past reservations that expired or closed without payment.",
        "bookings_section_confirmed_title": "Confirmed bookings",
        "bookings_section_confirmed_hint": "Paid and confirmed for departure.",
        "bookings_section_active_title": "Temporary reservations",
        "bookings_section_active_hint": "Reserved temporarily — pay before the deadline to confirm your seats.",
        "bookings_section_history_title": "History",
        "bookings_section_history_hint": "Reservations that expired or closed without payment.",
        "bookings_history_truncated_note": "{n} older past holds are hidden here to keep this list manageable. "
        "They are not deleted — open a booking by reference from your records if needed.",
        "no_bookings": "No bookings yet. Browse the catalog to reserve a tour.",
        "booking_seats_amount": "{amount} · {n} seat(s)",
        "booking_open": "Open",
        "loading_booking_detail": "Loading booking...",
        "booking_details_title": "Booking details",
        "cta_pay_now": "Pay now",
        "cta_browse_tours": "Browse tours",
        "cta_back_to_bookings": "Back to bookings",
        "help_title": "Help",
        "help_return_note": "Close the Mini App or switch back to the bot chat in Telegram anytime — "
        "the bot is your guide; this app is where you book and pay.",
        "loading_help": "Loading help...",
        "settings_title": "Language & settings",
        "settings_intro": "Choose the language for tour content and booking summaries. "
        "If a translation is missing, the app falls back and tells you.",
        "label_display_language": "Display language",
        "btn_save": "Save",
        "back": "Back",
        "payment_status_awaiting": "Payment pending",
        "payment_status_unpaid": "Not paid yet",
        "payment_status_paid": "Paid",
        "hold_no_deadline": "No payment deadline is set for this hold.",
        "hold_expired": "This reservation has expired. Return to the catalog to check availability.",
        "hold_time_left": "Time left to pay: about {hours}h {minutes}m (deadline {deadline}).",
        "days_hours": "{n} day(s)",
        "facade_active_booking": "Reserved temporarily",
        "facade_active_payment": "Payment pending — complete checkout to confirm your seats.",
        "facade_expired_booking": "Reservation expired",
        "facade_expired_payment": "The payment deadline passed before checkout was completed.",
        "facade_released_booking": "Reservation expired",
        "facade_released_payment": "This reservation closed without payment after the hold ended.",
        "facade_confirmed_booking": "Confirmed",
        "facade_confirmed_payment": "Paid — your booking is confirmed.",
        "facade_trip_booking": "Booking status",
        "facade_trip_payment": "Your trip — see details below.",
        "facade_other_booking": "Booking update",
        "facade_other_payment": "See booking details below.",
        "support_banner_title": "Need help?",
        "support_banner_body": "Need help with a booking or payment? Log a support request and, if needed, describe the issue in the bot chat.",
        "support_cta_log_request": "Log support request",
        "booking_support_body": "Need help with this booking? Log a support request and, if needed, describe your case in the bot chat.",
        "payment_support_body": "Payment or checkout problem? Log a support request — the team may review it later. This is not a live chat.",
        "support_request_success": "Support request recorded. Reference: {ref}",
        "support_request_error": "Could not record the support request right now. Please try again later.",
        "btn_custom_request": "Custom trip request",
        "custom_request_title": "Custom trip / group request",
        "custom_request_intro": "Use this for a different route, date, group size, or transport setup than a ready-made catalog departure. "
        "We send your details to suppliers as a request only — not a reservation, not payment, and not the waitlist. "
        "Edit the suggested text below so it matches what you need.",
        "custom_request_fields_legend": "Required: route / notes (at least a few characters). Optional: end date, group size, special notes. "
        "Dates use YYYY-MM-DD.",
        "custom_request_field_type": "Request type",
        "custom_request_field_start": "Travel date start (YYYY-MM-DD)",
        "custom_request_field_end": "Travel date end (optional)",
        "custom_request_field_route": "Route / destination / notes (required)",
        "custom_request_field_route_hint": "Describe what you need; you can edit the prefilled text from a catalog tour.",
        "custom_request_field_group": "Group size (optional)",
        "custom_request_field_special": "Special conditions (optional)",
        "custom_request_prefill_banner": "Context only: you were viewing catalog tour «{code}». This form still creates a separate custom request — it does not book that departure or join the waitlist.",
        "custom_request_prefill_route_template": "I was looking at ready-made catalog tour {code} — «{title}». I am interested in: ",
        "custom_request_submit": "Submit request",
        "custom_request_success": "Request recorded (id {id}). This is not a reservation.",
        "custom_request_success_title": "Request sent",
        "custom_request_success_lead": "Your custom trip request was recorded.",
        "custom_request_success_reference": "Reference number: #{id}",
        "custom_request_success_summary_type": "Type: {label}",
        "custom_request_success_summary_route": "Your notes: {text}",
        "custom_request_success_next": "Track status under My requests. No payment or confirmed booking exists until the normal catalog / Mini App flow says so.",
        "custom_request_error": "Could not submit the request. Check fields and try again.",
        "custom_request_from_help_hint": "Need something that is not in the catalog? Submit a structured custom request.",
        "custom_request_opt_group_trip": "Group trip",
        "custom_request_opt_custom_route": "Custom route",
        "custom_request_opt_other": "Other",
        "btn_done": "Done",
        "rfq_bridge_cta_from_success": "Continue booking (if an offer is ready)",
        "rfq_bridge_screen_title": "Booking from your request",
        "rfq_bridge_intro": "When the team has linked an offer to your custom request, you can hold seats here and continue to payment — only if self-service is allowed for this case.",
        "rfq_bridge_request_ref": "Request #{id}",
        "rfq_bridge_loading": "Loading booking options…",
        "rfq_bridge_assisted_heading": "We need to help you with this step",
        "rfq_bridge_platform_blocked_heading": "Online checkout is not available",
        "rfq_bridge_hold_section_title": "Hold is active",
        "rfq_bridge_hold_active_pay_blocked": "Your temporary hold is active, but paying inside the app is not available for this request. Use Help to reach the team, or follow their instructions. Do not pay here unless they confirm this channel.",
        "rfq_bridge_payment_blocked_generic": "Payment cannot continue in the app for this request. Use Help if you need assistance.",
        "rfq_bridge_expired_hold": "This hold is no longer active. Check the catalog for availability or contact the team about your request.",
        "rfq_bridge_eligibility_error": "Could not verify whether app checkout is allowed. You can try again or use Help.",
        "rfq_bridge_closed_booking_path": "This booking link is no longer active. Use My requests or My bookings if you still have a reservation, or contact the team.",
        "rfq_hub_detail_bridge_closed": "The booking link for this request was closed or replaced. If you still have a reservation, open it from My bookings or continue from your request detail.",
        "btn_my_requests": "My requests",
        "my_requests_title": "My requests",
        "my_requests_subtitle": "Custom trip requests only — separate from catalog checkout and from the waitlist. "
        "Booking and payment still use the normal catalog / Mini App flow unless a clear next step appears on a request.",
        "my_requests_loading": "Loading your requests…",
        "my_requests_empty": "You have no custom requests yet. Start one from Help, the “Custom or group trip” link in the app header, or a tour screen when offered.",
        "my_requests_row_view": "View details",
        "my_requests_row_followup_hint": "There may be a next step — open details.",
        "my_requests_row_review_hint": "Waiting on the team or a supplier — open details for the latest status.",
        "my_requests_list_summary_all_closed": "Everything here is closed or completed in the app — open a row only if you need the history.",
        "my_requests_list_summary_all_active": "These requests are still in progress — open a row for details and any next step the app can offer.",
        "my_requests_list_summary_mixed": "You have both active and closed requests. Closed ones usually need no further action here.",
        "my_requests_list_expectation_note": "We do not notify you for every change. When you are waiting, check My requests — any next step you can take in the app will show on the request detail.",
        "my_requests_row_hint_open": "Request received — review has not started yet.",
        "my_requests_row_hint_under_review": "In review — please wait; open details for the latest status.",
        "my_requests_row_hint_supplier_selected": "A supplier route is on record — open details to see if booking or payment is available.",
        "my_requests_row_hint_closed_assisted": "Closed with assistance — usually no further app step; open details for reference.",
        "my_requests_row_hint_closed_external": "Closed outside the app — follow the team’s instructions if you continue elsewhere.",
        "my_requests_row_hint_cancelled": "Cancelled — no further step unless you submit a new request.",
        "my_requests_row_hint_fulfilled": "Completed — open details for reference; use My bookings if you have a trip.",
        "my_requests_detail_next_heading": "What happens next",
        "my_requests_detail_next_pay_when_ready": "If app checkout is allowed for your hold, use Continue to payment below. If that button is missing, paying here may not be available — use Help if you are unsure.",
        "my_requests_detail_next_continue_booking": "You can continue the in-app booking flow when ready — use Continue booking below.",
        "my_requests_detail_next_open_booking": "You can open the linked booking below to review hold, payment, or trip status.",
        "my_requests_detail_next_cancelled": "This request is cancelled. Submit a new request if you still need something similar.",
        "my_requests_detail_next_closed": "This request is closed in the app. Use the detail above for reference; there is usually nothing else to do here.",
        "my_requests_detail_next_open": "Your request was received. Please wait while it is reviewed — check back here; we will show a next step when the app can offer one.",
        "my_requests_detail_next_under_review": "Review is in progress. Please wait — check back here; we will show a next step when the app can offer one.",
        "my_requests_detail_next_supplier_selected": "A supplier path is on record. Check the detail above and any button below — if nothing appears, the next step may be off-app; use Help if unsure.",
        "my_requests_detail_next_generic": "Read the status and notes above. If a button appears below, it is the current app-available next step; otherwise wait or use Help.",
        "my_requests_cta_caption_payment": "Continues checkout for the linked reservation when the server allows it — this is not a new booking by itself.",
        "my_requests_cta_caption_booking": "Opens the booking steps for the offer linked to this request.",
        "my_requests_cta_caption_open_booking": "Opens your existing booking for this tour (hold, payment, or confirmation).",
        "my_requests_detail_title": "Request details",
        "my_requests_detail_back": "Back to list",
        "my_requests_detail_type": "Type: {label}",
        "my_requests_detail_dates": "Travel dates: {start}{end}",
        "my_requests_detail_date_end": " → {end}",
        "my_requests_detail_summary": "Summary",
        "my_requests_detail_selected_offer_title": "Selected proposal (informational only)",
        "my_requests_detail_selected_price": "Quoted: {amount} {currency}",
        "my_requests_detail_selected_message": "{text}",
        "my_requests_detail_selected_modes": "How this proposal was declared: {sales} · {payment}",
        "my_requests_detail_status": "Progress: {label}",
        "my_requests_detail_bridge_line": "Booking link: {line}",
        "my_requests_cta_continue_booking": "Continue booking",
        "my_requests_cta_continue_payment": "Continue to payment",
        "my_requests_cta_open_booking": "Open booking",
        "rfq_status_open": "Sent — waiting to be reviewed",
        "rfq_status_under_review": "In review with the team or suppliers",
        "rfq_status_supplier_selected": "Supplier route chosen — check detail for next steps",
        "rfq_status_closed_assisted": "Closed (handled with assistance)",
        "rfq_status_closed_external": "Closed outside the app",
        "rfq_status_cancelled": "Cancelled",
        "rfq_status_fulfilled": "Completed — use My bookings if you have a linked trip",
        "rfq_type_group_trip": "Group trip",
        "rfq_type_custom_route": "Custom route",
        "rfq_type_other": "Other",
        "rfq_hub_detail_no_bridge": "No active booking link for this request yet. If you were told an offer is ready, check back later or use Help.",
        "rfq_hub_detail_self_service_yes": "You can continue booking in the app for the linked tour when you are ready.",
        "rfq_hub_detail_self_service_no": "Self-serve booking is not available for this request in the app. Use Help or wait for the team.",
    },
    "ro": {
        "catalog_title": "Catalog tururi",
        "catalog_subtitle": "Flux principal: navigheaza aici, apoi foloseste Rezervarile mele pentru status. "
        "Filtrele de mai jos sunt scurtaturi optionale ca in bot.",
        "btn_my_bookings": "Rezervarile mele",
        "btn_language_settings": "Limba si setari",
        "btn_help": "Ajutor",
        "nav_custom_trip": "Tur personalizat sau grup",
        "filters_heading": "Filtre",
        "label_destination": "Destinatie",
        "label_departure_from": "Plecare de la",
        "label_departure_to": "Plecare pana la",
        "label_max_price": "Pret max",
        "btn_apply_filters": "Aplica filtre",
        "btn_clear": "Sterge",
        "loading_tours": "Se incarca tururile...",
        "empty_catalog": "Niciun tur nu se potriveste. Incearca sa modifici filtrele.",
        "view_details": "Vezi detalii",
        "catalog_card_no_description": "Deschide ecranul de detalii pentru descrierea completa.",
        "badge_seats_available": "Locuri disponibile",
        "badge_sold_out": "Epuizat",
        "loading_tour_details": "Se incarca detaliile...",
        "back_to_catalog": "Inapoi la catalog",
        "settings": "Setari",
        "prepare_reservation": "Pregateste rezervarea",
        "catalog_card_assisted_notice": "Rezervarea charter (autocar complet) din catalog pentru această plecare nu este disponibilă în aplicație. Deschide detaliile pentru a continua cu echipa și finaliza rezervarea.",
        "detail_assisted_booking_title": "Continuă acest tur din catalog cu echipa",
        "detail_assisted_booking_body": "Nu poți finaliza singur în aplicație un hold pentru autocarul complet la această plecare. Folosește butonul de mai jos sau Ajutor — te ajutăm cu aceeași ofertă din catalog. "
        "Este asistență pentru rezervare din catalog, nu un flux separat de cerere personalizată sau oferte.",
        "btn_request_full_bus_assistance": "Contactează-ne despre acest tur din catalog",
        "mode2_custom_trip_hint": "Ai nevoie de alt traseu, altă dată sau altă configurație decât acest charter din catalog? Începe o cerere de tur personalizat — separată de această plecare; nu rezervă automat acest tur.",
        "btn_mode2_request_custom_trip": "Cerere tur personalizat",
        "preparation_assisted_title": "Charter din catalog — rezervarea autocarului complet nu este în self-service aici",
        "preparation_assisted_body": "Nu poți plăti sau plasa singur un hold pentru autocarul complet în aplicație la această plecare din catalog. Folosește Ajutor pentru a contacta echipa și continuă rezervarea cu asistență manuală.",
        "waitlist_intro_sold_out": "Acest tur este epuizat. Poti intra pe lista de asteptare pentru a inregistra interesul — "
        "aceasta nu este o rezervare confirmata sau un loc garantat.",
        "waitlist_join_cta": "Intră pe lista de așteptare",
        "waitlist_status_on": "Ești pe lista de așteptare pentru acest tur. Aceasta nu este o rezervare confirmată.",
        "waitlist_active_title": "Ești pe lista de așteptare",
        "waitlist_active_body": "Interesul tău este înregistrat pentru acest tur. Aceasta nu este o rezervare confirmată sau un loc garantat.",
        "waitlist_in_review_title": "Cererea ta pe lista de așteptare este în revizie",
        "waitlist_in_review_body": "Procesăm cererea ta. În continuare nu este o rezervare confirmată sau un loc garantat.",
        "waitlist_closed_body": "Cererea ta anterioară pe lista de așteptare pentru acest tur este închisă. Poți intra din nou pe listă dacă vrei să înregistrezi interes — tot nu este o rezervare confirmată.",
        "waitlist_tour_not_eligible": "Acest tur nu este deschis pentru rezervare sau lista de așteptare aici, acum.",
        "waitlist_snackbar_created": "Cererea pentru lista de așteptare a fost înregistrată. Aceasta nu este o rezervare confirmată.",
        "waitlist_snackbar_already": "Ești deja pe lista de așteptare pentru acest tur.",
        "waitlist_snackbar_not_eligible": "Lista de așteptare nu este disponibilă pentru acest tur acum.",
        "waitlist_snackbar_error": "Nu am putut înregistra cererea pentru lista de așteptare. Încearcă din nou mai târziu.",
        "section_boarding_points": "Puncte de imbarcare",
        "loading_reservation_options": "Se incarca optiunile...",
        "back_to_tour_details": "Inapoi la detalii tur",
        "label_seats": "Locuri",
        "label_boarding": "Punct imbarcare",
        "btn_preview_summary": "Previzualizeaza sumar",
        "btn_confirm_reservation": "Confirma rezervarea",
        "prep_summary_title": "Sumar pregatire",
        "loading_reservation": "Se incarca rezervarea...",
        "back_to_preparation": "Inapoi la pregatire",
        "reservation_confirmed_title": "Hold temporar confirmat",
        "reservation_hold_intro": "Hold-ul este activ și plata este încă necesară. Plătește acum înainte de termenul de mai jos sau locurile pot fi eliberate. Plata nu apare ca încheiată până nu o confirmă serverul.",
        "continue_to_payment": "Continua la plata",
        "line_reservation_ref": "Referinta rezervare: #{id}",
        "line_amount_to_pay": "De plata: {amount} {currency}",
        "line_payment_status": "Status plata: {status}",
        "starting_payment": "Se porneste plata...",
        "payment_title": "Plata",
        "payment_intro_active_hold": "Acest hold este inca activ. Finalizeaza plata inainte de termenul de mai jos — dupa aceea, locurile pot fi eliberate inapoi la tur.",
        "payment_screen_unavailable_hold": "Nu se poate porni plata pentru aceasta rezervare. Hold-ul poate fi expirat sau eliberat. Deschide Rezervarile mele pentru status, sau reincepe din catalog.",
        "payment_screen_load_error_generic": "Nu am putut incarca pasul de plata. Revino la Rezervarile mele sau incearca din nou.",
        "payment_mock_disabled_user_message": "Finalizarea de test a platii este oprita pe acest server. Rezervarea ramane neplatita pana confirma un operator sau webhook-ul. Pentru staging, echipa poate activa mock payment pe API, sau folositi canalul normal de plata cand e disponibil.",
        "payment_confirm_error_generic": "Plata nu a putut fi confirmata. Incearca din nou cat timp hold-ul e activ, sau verifica Rezervarile mele.",
        "booking_detail_note_active_hold": "Poti plati cat timp se aplica termenul de mai sus. Dupa confirmarea platii, rezervarea apare la Rezervari confirmate.",
        "booking_detail_note_confirmed": "Calatoria este platita si confirmata. Foloseste Rezervarile mele pentru detalii.",
        "booking_detail_note_inactive_unpaid_reservation": "Această rezervare nu mai este activă — hold-ul s-a încheiat fără plată finalizată. Pentru acest tur, începe o rezervare nouă din catalog dacă sunt locuri.",
        "booking_detail_note_other_status": "Verifică statusul de mai sus. Folosește Rezervările mele pentru actualizări sau trimite suport dacă ceva pare în neregulă.",
        "booking_detail_note_released": "Acest hold nu mai este activ (expirat sau eliberat fara plata). Pentru acest tur, fa o rezervare noua din catalog daca sunt locuri.",
        "line_pay_before": "Plateste inainte de: {when}",
        "line_reservation_expiry_na": "Termenul rezervarii nu este disponibil.",
        "line_amount_due": "Suma datorata: {amount} {currency}",
        "line_payment_session_ref": "Referinta sesiune plata: {ref}",
        "payment_stub_notice": "Plata prin provider in aceasta aplicatie nu e conectata inca. "
        "Plateste acum explica pasul urmator; plata nu e confirmata pana nu o confirma serverul.",
        "payment_success_title": "Plata confirmata",
        "payment_success_intro": "Serverul a inregistrat plata. Locurile tale sunt confirmate pentru aceasta plecare.",
        "payment_success_booking_status": "Status rezervare: confirmata.",
        "pay_now": "Plateste acum",
        "loading_bookings": "Se incarca rezervarile...",
        "my_bookings_title": "Rezervarile mele",
        "my_bookings_subtitle": "Mai întâi călătoriile confirmate, apoi rezervările temporare de plătit, apoi istoricul (expirate sau închise fără plată).",
        "bookings_section_confirmed_title": "Rezervari confirmate",
        "bookings_section_confirmed_hint": "Platite si confirmate pentru plecare.",
        "bookings_section_active_title": "Rezervări temporare",
        "bookings_section_active_hint": "Rezervare temporară — plătește înainte de termen pentru a confirma locurile.",
        "bookings_section_history_title": "Istoric",
        "bookings_section_history_hint": "Rezervări expirate sau închise fără plată.",
        "bookings_history_truncated_note": "{n} rezervari vechi din istoric sunt ascunse aici pentru o lista mai clara. "
        "Nu sunt sterse — poti deschide o rezervare dupa referinta daca ai nevoie.",
        "no_bookings": "Inca nu ai rezervari. Deschide catalogul.",
        "booking_seats_amount": "{amount} · {n} loc(uri)",
        "booking_open": "Deschide",
        "loading_booking_detail": "Se incarca rezervarea...",
        "booking_details_title": "Detalii rezervare",
        "cta_pay_now": "Plateste acum",
        "cta_browse_tours": "Vezi tururi",
        "cta_back_to_bookings": "Inapoi la rezervari",
        "help_title": "Ajutor",
        "help_return_note": "Poti inchide Mini App sau reveni la chat-ul botului in Telegram oricand — "
        "botul este ghidul; aici plasezi rezervarea si plata.",
        "loading_help": "Se incarca ajutorul...",
        "settings_title": "Limba si setari",
        "label_display_language": "Limba afisaj",
        "btn_save": "Salveaza",
        "back": "Inapoi",
        "payment_status_awaiting": "Plată în așteptare",
        "payment_status_unpaid": "Neplatit",
        "payment_status_paid": "Platit",
        "hold_no_deadline": "Nu exista termen de plata setat.",
        "hold_expired": "Această rezervare a expirat. Revino la catalog.",
        "hold_time_left": "Timp ramas pentru plata: ~{hours}h {minutes}m (limita {deadline}).",
        "days_hours": "{n} zi(le)",
        "facade_active_booking": "Rezervată temporar",
        "facade_active_payment": "Plata este în așteptare — finalizează checkout-ul pentru a confirma locurile.",
        "facade_expired_booking": "Rezervare expirată",
        "facade_expired_payment": "Termenul de plată a trecut înainte de finalizarea checkout-ului.",
        "facade_released_booking": "Rezervare expirată",
        "facade_released_payment": "Rezervarea s-a închis fără plată după încheierea hold-ului.",
        "facade_confirmed_booking": "Confirmat",
        "facade_confirmed_payment": "Platit — rezervare confirmata.",
        "facade_trip_booking": "Status rezervare",
        "facade_trip_payment": "Calatoria ta — vezi detaliile.",
        "facade_other_booking": "Actualizare rezervare",
        "facade_other_payment": "Vezi detaliile rezervarii.",
        "support_banner_title": "Ai nevoie de ajutor?",
        "support_banner_body": "Ai nevoie de ajutor cu o rezervare sau o plată? Trimite o cerere de suport și, dacă este nevoie, descrie problema și în chatul botului.",
        "support_cta_log_request": "Trimite cerere de suport",
        "booking_support_body": "Ai nevoie de ajutor cu această rezervare? Trimite o cerere de suport și, dacă este nevoie, descrie cazul și în chatul botului.",
        "payment_support_body": "Problemă la plată sau la checkout? Trimite o cerere de suport — echipa o poate analiza ulterior. Acesta nu este un chat live.",
        "support_request_success": "Cererea de suport a fost înregistrată. Referință: {ref}",
        "support_request_error": "Cererea de suport nu a putut fi înregistrată acum. Încearcă din nou mai târziu.",
        "btn_custom_request": "Cerere personalizată",
        "custom_request_title": "Cerere excursie / grup",
        "custom_request_intro": "Folosește acest formular pentru alt traseu, altă dată, altă mărime de grup sau alt aranjament decât o plecare fixă din catalog. "
        "Trimitem detaliile către furnizori ca cerere — nu e rezervare, nu e plată și nu e lista de așteptare. "
        "Editează textul sugerat ca să reflecte ce ai nevoie.",
        "custom_request_fields_legend": "Obligatoriu: rută / note (minimum câteva caractere). Opțional: dată sfârșit, mărime grup, note speciale. "
        "Folosește AAAA-LL-ZZ pentru date.",
        "custom_request_field_type": "Tip cerere",
        "custom_request_field_start": "Data început (AAAA-LL-ZZ)",
        "custom_request_field_end": "Data sfârșit (opțional)",
        "custom_request_field_route": "Rută / destinație / note (obligatoriu)",
        "custom_request_field_route_hint": "Descrie ce ai nevoie; poți edita textul precompletat de la un tur din catalog.",
        "custom_request_field_group": "Mărime grup (opțional)",
        "custom_request_field_special": "Condiții speciale (opțional)",
        "custom_request_prefill_banner": "Doar context: te uitai la turul din catalog «{code}». Formularul creează în continuare o cerere separată — nu rezervă acea plecare și nu intră pe lista de așteptare.",
        "custom_request_prefill_route_template": "Mă uitam la turul din catalog {code} — «{title}». Mă interesează: ",
        "custom_request_submit": "Trimite cererea",
        "custom_request_success": "Cerere înregistrată (id {id}). Nu este o rezervare.",
        "custom_request_success_title": "Cerere trimisă",
        "custom_request_success_lead": "Cererea ta personalizată a fost înregistrată.",
        "custom_request_success_reference": "Număr referință: #{id}",
        "custom_request_success_summary_type": "Tip: {label}",
        "custom_request_success_summary_route": "Notele tale: {text}",
        "custom_request_success_next": "Urmărește statusul la Cererile mele. Nu există plată sau rezervare confirmată până nu o spune fluxul normal din catalog / Mini App.",
        "custom_request_error": "Nu am putut trimite cererea. Verifică câmpurile și încearcă din nou.",
        "custom_request_from_help_hint": "Ai nevoie de ceva ce nu e în catalog? Trimite o cerere structurată.",
        "custom_request_opt_group_trip": "Excursie grup",
        "custom_request_opt_custom_route": "Rută personalizată",
        "custom_request_opt_other": "Altele",
        "btn_done": "Gata",
        "rfq_bridge_cta_from_success": "Continuă rezervarea (dacă există ofertă)",
        "rfq_bridge_screen_title": "Rezervare din cererea ta",
        "rfq_bridge_intro": "Când echipa leagă o ofertă de cererea ta personalizată, poți bloca locuri aici și continua la plată — doar dacă self-service este permis pentru acest caz.",
        "rfq_bridge_request_ref": "Cerere #{id}",
        "rfq_bridge_loading": "Se încarcă opțiunile de rezervare…",
        "rfq_bridge_assisted_heading": "Avem nevoie să te ajutăm la acest pas",
        "rfq_bridge_platform_blocked_heading": "Checkout online indisponibil",
        "rfq_bridge_hold_section_title": "Hold activ",
        "rfq_bridge_hold_active_pay_blocked": "Rezervarea temporară este activă, dar plata în aplicație nu este disponibilă pentru această cerere. Folosește Ajutor pentru echipă sau urmează instrucțiunile lor. Nu plăti aici decât dacă confirmă acest canal.",
        "rfq_bridge_payment_blocked_generic": "Plata nu poate continua în aplicație pentru această cerere. Folosește Ajutor dacă ai nevoie de asistență.",
        "rfq_bridge_expired_hold": "Acest hold nu mai este activ. Verifică catalogul sau contactează echipa pentru cererea ta.",
        "rfq_bridge_eligibility_error": "Nu am putut verifica dacă plata în aplicație este permisă. Poți reîncerca sau folosi Ajutor.",
        "rfq_bridge_closed_booking_path": "Această legătură de rezervare nu mai este activă. Folosește Cererile mele sau Rezervările mele dacă ai încă o rezervare, sau contactează echipa.",
        "btn_my_requests": "Cererile mele",
        "my_requests_title": "Cererile mele",
        "my_requests_subtitle": "Doar cereri de tur personalizat — separate de checkout-ul din catalog și de lista de așteptare. "
        "Rezervarea și plata rămân prin fluxul normal din catalog / Mini App decât dacă apare un pas clar la o cerere.",
        "my_requests_loading": "Se încarcă cererile…",
        "my_requests_empty": "Încă nu ai cereri personalizate. Poți începe din Ajutor, din linkul „Tur personalizat sau grup” din antet sau de pe un tur când e oferit.",
        "my_requests_row_view": "Vezi detalii",
        "my_requests_row_followup_hint": "Poate exista un pas următor — deschide detaliile.",
        "my_requests_row_review_hint": "În așteptarea echipei sau a unui furnizor — deschide detaliile pentru status.",
        "my_requests_list_summary_all_closed": "Tot ce vezi aici este închis sau finalizat în aplicație — deschide un rând doar dacă ai nevoie de istoric.",
        "my_requests_list_summary_all_active": "Aceste cereri sunt încă în lucru — deschide un rând pentru detalii și orice pas pe care îl poate oferi aplicația.",
        "my_requests_list_summary_mixed": "Ai cereri active și închise. Cele închise de obicei nu mai necesită acțiune aici.",
        "my_requests_list_expectation_note": "Nu trimitem o notificare la fiecare modificare. Când aștepți un răspuns, verifică Cererile mele — orice pas disponibil în aplicație apare la detaliul cererii.",
        "my_requests_row_hint_open": "Cerere primită — încă nu a început revizuirea.",
        "my_requests_row_hint_under_review": "În analiză — așteaptă; deschide detaliile pentru statusul curent.",
        "my_requests_row_hint_supplier_selected": "Există un traseu de furnizor înregistrat — deschide detaliile pentru rezervare sau plată, dacă e cazul.",
        "my_requests_row_hint_closed_assisted": "Închisă cu asistență — de obicei fără alt pas în aplicație; deschide detaliile pentru referință.",
        "my_requests_row_hint_closed_external": "Închisă în afara aplicației — dacă continui altundeva, urmează instrucțiunile echipei.",
        "my_requests_row_hint_cancelled": "Anulată — nu mai e nimic de făcut decât dacă trimiți o cerere nouă.",
        "my_requests_row_hint_fulfilled": "Finalizată — deschide detaliile pentru referință; folosește Rezervările mele dacă ai excursie.",
        "my_requests_detail_next_heading": "Ce urmează",
        "my_requests_detail_next_pay_when_ready": "Dacă plata în aplicație este permisă pentru hold, folosește Continuă la plată mai jos. Dacă butonul lipsește, plata aici poate să nu fie disponibilă — folosește Ajutor dacă nu ești sigur.",
        "my_requests_detail_next_continue_booking": "Poți continua fluxul de rezervare în aplicație când ești gata — folosește Continuă rezervarea mai jos.",
        "my_requests_detail_next_open_booking": "Poți deschide rezervarea legată mai jos pentru hold, plată sau statusul excursiei.",
        "my_requests_detail_next_cancelled": "Cererea este anulată. Trimite o cerere nouă dacă mai ai nevoie de ceva similar.",
        "my_requests_detail_next_closed": "Cererea este închisă în aplicație. Folosește detaliile de mai sus ca referință; de obicei nu mai e nimic de făcut aici.",
        "my_requests_detail_next_open": "Cererea a fost primită. Așteaptă revizuirea — revino aici; vom arăta un pas următor când aplicația îl poate oferi.",
        "my_requests_detail_next_under_review": "Revizuirea este în curs. Așteaptă — revino aici; vom arăta un pas următor când aplicația îl poate oferi.",
        "my_requests_detail_next_supplier_selected": "Există un traseu de furnizor înregistrat. Verifică detaliile de mai sus și orice buton de mai jos — dacă nu apare nimic, pasul următor poate fi în afara aplicației; folosește Ajutor dacă nu ești sigur.",
        "my_requests_detail_next_generic": "Citește statusul și notele de mai sus. Dacă apare un buton mai jos, acela este pasul curent disponibil în aplicație; altfel așteaptă sau folosește Ajutor.",
        "my_requests_cta_caption_payment": "Continuă checkout-ul pentru rezervarea legată când serverul permite — nu este o rezervare nouă prin ea însă.",
        "my_requests_cta_caption_booking": "Deschide pașii de rezervare pentru oferta legată de această cerere.",
        "my_requests_cta_caption_open_booking": "Deschide rezervarea existentă pentru acest tur (hold, plată sau confirmare).",
        "my_requests_detail_title": "Detalii cerere",
        "my_requests_detail_back": "Înapoi la listă",
        "my_requests_detail_type": "Tip: {label}",
        "my_requests_detail_dates": "Date călătorie: {start}{end}",
        "my_requests_detail_date_end": " → {end}",
        "my_requests_detail_summary": "Rezumat",
        "my_requests_detail_selected_offer_title": "Propunere selectată (doar informativ)",
        "my_requests_detail_selected_price": "Ofertă: {amount} {currency}",
        "my_requests_detail_selected_message": "{text}",
        "my_requests_detail_selected_modes": "Declarat de furnizor: {sales} · {payment}",
        "my_requests_detail_status": "Progres: {label}",
        "my_requests_detail_bridge_line": "Legătură rezervare: {line}",
        "my_requests_cta_continue_booking": "Continuă rezervarea",
        "my_requests_cta_continue_payment": "Continuă la plată",
        "my_requests_cta_open_booking": "Deschide rezervarea",
        "rfq_status_open": "Trimisă — în așteptarea analizei",
        "rfq_status_under_review": "În analiză la echipă sau furnizori",
        "rfq_status_supplier_selected": "Traseu furnizor ales — vezi detaliile pentru pașii următori",
        "rfq_status_closed_assisted": "Închisă (cu asistență)",
        "rfq_status_closed_external": "Închisă în afara aplicației",
        "rfq_status_cancelled": "Anulată",
        "rfq_status_fulfilled": "Finalizată — folosește Rezervările mele dacă ai excursie legată",
        "rfq_type_group_trip": "Excursie grup",
        "rfq_type_custom_route": "Rută personalizată",
        "rfq_type_other": "Altele",
        "rfq_hub_detail_no_bridge": "Încă nu există o legătură activă de rezervare pentru această cerere. Dacă ți s-a spus că oferta e gata, revino mai târziu sau folosește Ajutor.",
        "rfq_hub_detail_self_service_yes": "Poți continua rezervarea în aplicație pentru turul legat când ești gata.",
        "rfq_hub_detail_self_service_no": "Rezervarea self-serve nu e disponibilă în aplicație pentru această cerere. Folosește Ajutor sau așteaptă echipa.",
        "rfq_hub_detail_bridge_closed": "Legătura de rezervare pentru această cerere a fost închisă sau înlocuită. Dacă ai încă o rezervare, deschide-o din Rezervările mele sau continuă din detaliul cererii.",
    },
    "ru": {
        "support_banner_title": "Нужна помощь?",
        "support_banner_body": "Нужна помощь с бронированием или оплатой? Отправьте запрос в поддержку и, при необходимости, опишите проблему в чате бота.",
        "support_cta_log_request": "Отправить запрос в поддержку",
        "booking_support_body": "Нужна помощь по этому бронированию? Отправьте запрос в поддержку и, при необходимости, опишите ситуацию в чате бота.",
        "payment_support_body": "Проблема с оплатой или checkout? Отправьте запрос в поддержку — команда сможет проверить его позже. Это не онлайн-чат.",
        "support_request_success": "Запрос в поддержку зарегистрирован. Номер: {ref}",
        "support_request_error": "Сейчас не удалось зарегистрировать запрос в поддержку. Попробуйте позже.",
    },
    "sr": {
        "support_banner_title": "Treba vam pomoć?",
        "support_banner_body": "Treba vam pomoć oko rezervacije ili plaćanja? Pošaljite zahtev za podršku i, ako je potrebno, opišite problem i u četu bota.",
        "support_cta_log_request": "Pošalji zahtev za podršku",
        "booking_support_body": "Treba vam pomoć oko ove rezervacije? Pošaljite zahtev za podršku i, ako je potrebno, opišite slučaj i u četu bota.",
        "payment_support_body": "Imate problem sa plaćanjem ili checkout-om? Pošaljite zahtev za podršku — tim ga može pregledati kasnije. Ovo nije live chat.",
        "support_request_success": "Zahtev za podršku je evidentiran. Referenca: {ref}",
        "support_request_error": "Zahtev za podršku trenutno nije moguće evidentirati. Pokušajte ponovo kasnije.",
    },
    "hu": {
        "support_banner_title": "Segítségre van szüksége?",
        "support_banner_body": "Segítségre van szüksége foglalással vagy fizetéssel kapcsolatban? Küldjön támogatási kérelmet, és ha szükséges, írja le a problémát a bot chatben is.",
        "support_cta_log_request": "Támogatási kérelem küldése",
        "booking_support_body": "Segítségre van szüksége ezzel a foglalással kapcsolatban? Küldjön támogatási kérelmet, és ha szükséges, írja le az esetet a bot chatben is.",
        "payment_support_body": "Fizetési vagy checkout probléma van? Küldjön támogatási kérelmet — a csapat később átnézheti. Ez nem élő chat.",
        "support_request_success": "A támogatási kérelem rögzítve. Azonosító: {ref}",
        "support_request_error": "A támogatási kérelmet most nem sikerült rögzíteni. Kérjük, próbálja újra később.",
    },
    "it": {
        "support_banner_title": "Hai bisogno di aiuto?",
        "support_banner_body": "Hai bisogno di aiuto con una prenotazione o un pagamento? Invia una richiesta di supporto e, se necessario, descrivi il problema anche nella chat del bot.",
        "support_cta_log_request": "Invia richiesta di supporto",
        "booking_support_body": "Hai bisogno di aiuto per questa prenotazione? Invia una richiesta di supporto e, se necessario, descrivi il caso anche nella chat del bot.",
        "payment_support_body": "Hai un problema con il pagamento o il checkout? Invia una richiesta di supporto — il team potrà esaminarla in seguito. Questa non è una chat live.",
        "support_request_success": "Richiesta di supporto registrata. Riferimento: {ref}",
        "support_request_error": "Non è stato possibile registrare la richiesta di supporto in questo momento. Riprova più tardi.",
    },
    "de": {
        "support_banner_title": "Brauchen Sie Hilfe?",
        "support_banner_body": "Brauchen Sie Hilfe bei einer Buchung oder Zahlung? Senden Sie eine Support-Anfrage und beschreiben Sie das Problem bei Bedarf auch im Bot-Chat.",
        "support_cta_log_request": "Support-Anfrage senden",
        "booking_support_body": "Brauchen Sie Hilfe bei dieser Buchung? Senden Sie eine Support-Anfrage und beschreiben Sie Ihren Fall bei Bedarf auch im Bot-Chat.",
        "payment_support_body": "Gibt es ein Problem mit der Zahlung oder dem Checkout? Senden Sie eine Support-Anfrage — das Team kann sie später prüfen. Dies ist kein Live-Chat.",
        "support_request_success": "Support-Anfrage wurde erfasst. Referenz: {ref}",
        "support_request_error": "Die Support-Anfrage konnte im Moment nicht erfasst werden. Bitte versuchen Sie es später erneut.",
    },
}


# Maps MiniAppBookingFacadeState value -> (booking_line_key, payment_line_key) in _STR tables.
_BOOKING_FACADE_SHELL_KEYS: dict[str, tuple[str, str]] = {
    "active_temporary_reservation": ("facade_active_booking", "facade_active_payment"),
    "expired_temporary_reservation": ("facade_expired_booking", "facade_expired_payment"),
    "cancelled_no_payment": ("facade_released_booking", "facade_released_payment"),
    "confirmed": ("facade_confirmed_booking", "facade_confirmed_payment"),
    "in_trip_pipeline": ("facade_trip_booking", "facade_trip_payment"),
    "other": ("facade_other_booking", "facade_other_payment"),
}


def booking_facade_labels(lang: str | None, facade_state: str) -> tuple[str, str]:
    """Localized booking title + payment line for My bookings / detail (API also sends English labels)."""
    bk, pk = _BOOKING_FACADE_SHELL_KEYS.get(
        facade_state,
        ("facade_other_booking", "facade_other_payment"),
    )
    return shell(lang, bk), shell(lang, pk)


def shell(lang: str | None, key: str, **kwargs: str) -> str:
    """Resolve UI-shell string; unknown language falls back to English."""
    code = (lang or "en").lower().split("-")[0]
    table = _STR.get(code, _STR["en"])
    template = table.get(key) or _STR["en"][key]
    return template.format(**kwargs) if kwargs else template


def hold_timer_hint(
    expires_at: datetime | None,
    lang: str | None,
    *,
    format_dt: Callable[[datetime], str],
) -> str:
    if expires_at is None:
        return shell(lang, "hold_no_deadline")
    now = datetime.now(UTC)
    end = expires_at if expires_at.tzinfo else expires_at.replace(tzinfo=UTC)
    if end <= now:
        return shell(lang, "hold_expired")
    total_minutes = max(0, int((end - now).total_seconds() // 60))
    hours, minutes = divmod(total_minutes, 60)
    return shell(
        lang,
        "hold_time_left",
        hours=str(hours),
        minutes=str(minutes),
        deadline=format_dt(expires_at),
    )


def payment_status_label(lang: str | None, status: object) -> str:
    """Map payment status enum/value to localized short label."""
    v = getattr(status, "value", status)
    if not isinstance(v, str):
        v = str(v)
    mapping = {
        "awaiting_payment": "payment_status_awaiting",
        "unpaid": "payment_status_unpaid",
        "paid": "payment_status_paid",
    }
    sk = mapping.get(v)
    if sk:
        return shell(lang, sk)
    return v.replace("_", " ").title()
